### ISSUE TITLE
Magento works too slow after installing the module 

### ISSUE THREAD

**Issue by Tonop** [karliuka/m2.MultiFlatShipping#1]
### Preconditions

Magento: 2.1.6
PHP: 5.6.26
MySQL: 14.14 Distrib 5.7.15

### Steps to reproduce
1.Install module
2.Go to checkout
### Expected result
The speed of the system is not changed
### Actual result
Module affects the system and causes it to work slowly.

**Comment by karliuka** [comment]
This module simply has no reason to slow down the system. I checked a minimum of 4(php5.6.23-php7) installations(magento 2.1.6) **and nowhere saw the speed problem**.

**Comment by Tonop** [comment]
Ok I will check again.
How to install the module to app/code , not to vendor folder?
And how to uninstall it?

**Comment by karliuka** [comment]
uninstalling the module:
composer remove faonni/module-shipping-multi-flat

**Comment by Tonop** [comment]
Reinstalled the module. Works as sxpected without affecting performance of system.
